### ISSUE TITLE
Not working with dunst

### ISSUE THREAD

**Issue by naurissteins** [daltomi/moc_notify#1]
Hi,

Do i need an additional configurations to get this work with dunst? 
For some reason it just doesn't work.

Cheers

**Comment by daltomi** [comment]
Hi,
I am using dunst and it works.
 1) Check that the script `onsongchange.sh` has execution permissions, if it does not have `MOC` it will fail.
 2) Look at the `syslog`  to confirm an error (on systems with `systemd` with `journalctl`) for example:
  ```bash
user.err: Jun 20 12:31:57 mocp: Error when running OnSongChange command '~/.moc/onsongchange.sh': Permission denied
...
user.err: Jun 20 12:28:08 moc_notify: Error: Failed mkfifo /tmp/moc_notify, error=File exists
  ```
Cheers

Edit: 
See [how-to-test-without-using-moc](https://github.com/daltomi/moc_notify#how-to-test-without-using-moc)

**Comment by naurissteins** [comment]
Hi,

Thanks for the explanation.

1. It has execution permissions
2. Error did not found

I tested `OnSongChange` with `echo Hello World! >> /home/arch/.moc/test.txt` and it works.

```
$ ps aux | grep moc_notify
arch        9549  0.0  0.0  19868  2272 pts/2    Sl+  21:51   0:00 ./moc_notify
```
I have no idea what i'm doing wrong then. 
I'm on ArchLinux if it makes any sense.

Cheers

**Comment by daltomi** [comment]
> $ ps aux | grep moc_notify
> arch        9549  0.0  0.0  19868  2272 pts/2    Sl+  21:51   0:00 ./moc_notify

Here I see a problem, it seems that `moc_notify` is not installed in the system (through AUR) and the script `onsonchange.sh` also executes `moc_notify`to know the name of the FIFO, see: https://github.com/daltomi/moc_notify/blob/0b3e2595811322f720365743e14d0119851510a8/scripts/onsongchange.sh#L23

If you prefer not to install it, you can change that line to:
```bash
FIFO=/tmp/moc_notify 
```

**Comment by daltomi** [comment]
Sorry, I need to work more on the README. What happened is that it indicated it before but I stopped using ArchLinux and I removed that reference, now I am back.

**Comment by naurissteins** [comment]
I didn't know that it's on AUR repository, hehe. 
It works now! Thank you very much :)

**Comment by daltomi** [comment]
Thanks to you!, greetings
